### ISSUE TITLE
Create a home page

### ISSUE THREAD

**Issue by rrickgauer** [rrickgauer/DotNetTasks#182]
Has links to:

- GitHub repo
- Website
- Wpf pages
- Author

### Todos

- [x] Add page links
- [x] Add new icon
- [ ] Add cli args for production/dev
