### ISSUE TITLE
Create an initial checklist setting page

### ISSUE THREAD

**Issue by rrickgauer** [rrickgauer/DotNetTasks#255]
- [ ] Edit checklist's metadata
- [ ] Delete the checklist
- [ ] Clone the checklist
- [ ] Add section for interacting with its items
- [ ] Edit label assignments
