### ISSUE TITLE
Display items in open checklist controls

### ISSUE THREAD

**Issue by rrickgauer** [rrickgauer/DotNetTasks#256]
- [x] Display all items
- [x] mark items complete
- [x] edit item's content
- [x] delete an item
- [x] add a new item
