### ISSUE TITLE
[CLI] Checklist Items

### ISSUE THREAD

**Issue by rrickgauer** [rrickgauer/DotNetTasks#273]
- [x] Edit an item
- [x] List items (table)
- [x] New item
- [x] Delete an item
- [x] Save list items (table) to output file
- [x] List items: show Complete/Incomplete/All

**Comment by rrickgauer** [comment]
testing comment

**Comment by rrickgauer** [comment]
To create a new item:

```sh
new --content=
```


To edit an item:

```sh
edit [ref] --content=
```


To delete an item:

```sh
delete [ref] --force
```


To mark an item complete/incomplete:

```sh
complete [ref] --incomplete
```


To toggle an item's is complete value:

```sh
toggle [ref]
```
