### ISSUE TITLE
Assign labels to events

### ISSUE THREAD

**Issue by rrickgauer** [rrickgauer/DotNetTasks#41]
Add ability for users to create custom labels and assign them to events. Then, users can filter their weekly recurrences by label.

## Todo

- [x] SQL: create tables to record user labels
- [x] API: create labels endpoints
- [x] GUI: create page to view/edit/delete labels
- [x] Create the workflow for creating a new label
- [x] Create the workflow for editing an existing label
- [x] Create the workflow for deleting an event
- [x] API: create an endpoint where you can assign multiple labels to an event in one call
- [x] Assign labels to an event
- [x] GUI: display the event's label assignments in the weekly recurrences board
- [ ] Filter weekly recurrences by label

**Comment by rrickgauer** [comment]
Users can assign multiple labels to an event.

**Comment by rrickgauer** [comment]
### HTML Color Picker Libraries

* https://simonwep.github.io/pickr/

**Comment by rrickgauer** [comment]
For the SQL tables, need to make 2 tables: Labels and Event_Labels

**Comment by rrickgauer** [comment]
Api Endpoint for labels:

```
api.tasks.com/labels
```

**Comment by rrickgauer** [comment]
Try using the new base response class for the services, and using IEnumerable instead of a list.

**Comment by rrickgauer** [comment]
![image](https://user-images.githubusercontent.com/22210580/188180408-1381aa45-d6ac-4ffd-a8d6-306fa919f1cc.png)

**Comment by rrickgauer** [comment]
Sql command to modify an Event_Label 

```sql
REPLACE INTO Event_Labels (event_id, label_id, created_on)
SELECT
    '049a10f7-53f1-4cdf-b906-31cfb4e8a148' AS event_id,
    '7bb42426-c172-4ffe-a973-954ed6723557' AS label_id,
    now()
WHERE
    EXISTS (
        SELECT
            1
        FROM
            Events e
        WHERE
            e.id = '049a10f7-53f1-4cdf-b906-31cfb4e8a147'
            AND e.user_id = 'b3406658-9721-4497-9eb6-784ed8555ac8'
    )
    AND EXISTS (
        SELECT
            1
        FROM
            Labels l
        WHERE
            l.id = '7bb42426-c172-4ffe-a973-954ed6723557'
            AND l.user_id = 'b3406658-9721-4497-9eb6-784ed8555ac8'
    );
```

**Comment by rrickgauer** [comment]
When you open the labels modal, js needs to make 2 calls to the api: 

1. a list of all the user's labels html for the form
1. a list of all the assigned labels for the event html

**Comment by rrickgauer** [comment]
Batch insert for API


```
PUT: /events/:eventId/labels
```

- removes all existing label assignments for the event
- request body should be a json list of label ids to assign to the event

**Comment by rrickgauer** [comment]
I think I'll need to make another endpoint for fetching all the event-label assignments in 1 api call

**Comment by rrickgauer** [comment]
To filter out the recurrences board by labels, add a query parm to recurrences request: `labels`.

This will be a comma separated list of label ids.

**Comment by rrickgauer** [comment]
Next step: update the js board controller to take in the labels url parms to send to the api
