### ISSUE TITLE
Have an automated system that sends daily event recurrences each day to users' emails

### ISSUE THREAD

**Issue by rrickgauer** [rrickgauer/DotNetTasks#88]
* Get a list of user ids that have a confirmed email and elected to receive daily task reminder emails
  * probably need to create a new method in the `IUserServices` interface for fetching these types of users
* Setup a new account settings section where users can elect to receive these emails
* Use `IRecurrencesServices.GetRecurrencesAsync` to get a list of each user's daily recurrences for the current day
* Send an email to each of the users with their recurrences in them
* The bottom of the email should have a link to the website and a link to unsubscribe for emails

## Tasks

- [x] API: setup a new console project that is responsible for sending out the emails
- [x] API: setup a cli arg class for the console app
- [x] API: add a column to the `Users` sql table denoting that a user would like to receive daily task emails
- [x] API: create a new method in `IUserServices` that returns a collection of users that should be emailed their daily tasks
- [x] API: create a new email message implementation for daily task reminders
- [x] GUI: add a new account settings page form to modify their election of daily task emails
- [ ] VPS: setup a cron job to automatically run the tasks.reminders application

**Comment by rrickgauer** [comment]
To run the console app:

```sh
C:\xampp\htdocs\files\DotNetTasks\src\Tasks\Tasks.Reminders\bin\Debug\net6.0\Tasks.Reminders.exe
```

**Comment by rrickgauer** [comment]
For the CLI parser see 

- #96 
- GitHub repo (https://github.com/commandlineparser/commandline)

**Comment by rrickgauer** [comment]
![image](https://user-images.githubusercontent.com/22210580/187578718-f321e116-4842-44ff-9caa-39f0d55154be.png)

Instead of doing this, write 1 sql command that retrieves all the recurrences for all users who are confirmed.
